### ISSUE TITLE
Problema com solução analítica

### ISSUE THREAD

**Issue by Erickslb** [fccoelho/Modelagem-Matematica-IV#10]
Professor, estamos com uns problemas na parte dos resultados.

Na solução analítica obtivemos vários erros, mesmo fazendo semelhante ao que foi feito em aula. Você poderia dar uma olhada no issue que abrimos com o erro e o output obtido no  nosso repositório, por favor?

**Comment by fccoelho** [comment]
@Erickslb, Vocês podiam colocar aqui  o link para o arquivo problemático?

**Comment by RaphaLevy** [comment]
https://github.com/RaphaLevy/Artigo_Fenomenos_Biologicos/blob/main/code/Codigo_A2.ipynb

**Comment by fccoelho** [comment]
Respondi lá no seu repo, @RaphaLevy
