### ISSUE TITLE
Análise dimensional não bate com a do artigo

### ISSUE THREAD

**Issue by Caioflp** [fccoelho/Modelagem-Matematica-IV#5]
Professor, eu e a Juliane estamos com alguma dificuldade para fazer a análise dimensional do modelo proposto no [artigo](https://github.com/fccoelho/Modelagem-Matematica-IV/files/7190861/kirschner1997.pdf)
 que escolhemos.
As unidades de medida que encontramos para algumas constantes são diferentes das informadas pelo artigo.

Nossos compartimentos são as populações de Vírus HIV ( V(t) ) e de células T ( T (t) e T_s (t) ) no sangue de uma pessoa, medidas em indivíduos por mm^3. Logo, a unidade de medida para essas quantias é mm^-3.
Agora, por exemplo, na página 27, na equação para S(t), a constante B_s é somada com V(t). Com isso, concluímos que a unidade de medida de B_s também deve ser mm^-3. Entretanto na tabela da página 29, é colocado que a unidade de medida de B_s é mm^3.

Praticamente todas unidades de medida que encontramos diferem das informadas pelo artigo.
Gostaríamos de saber se estamos fazendo errado.

**Comment by fccoelho** [comment]
Caio,

Pode ser que haja algum erro no artigo, façam análise como acreditam ser
correto e vou corrigir com base nisso, e não se está igual ao artigo.

abcs
