### ISSUE TITLE
Simulações não batem com as do artigo

### ISSUE THREAD

**Issue by Caioflp** [fccoelho/Modelagem-Matematica-IV#8]
Professor, estamos utilizando o Sage para solucionar numericamente o sistema de EDOs do artigo escolhido.

Para verificar se estava tudo certo, tentamos replicar algumas simulações apresentadas no artigo, utilizando os valores de parâmetros e condições iniciais relatadas no texto.

Entretanto, os plots que obtemos ficaram muito diferentes e, honestamente, não fazem tanto sentido.

Verificamos várias vezes se o sistema foi especificado corretamente e se colocamos os valores corretos para parâmetros/ condições iniciais, mas não encontramos nenhum erro na nossa implementação.

Também testamos diferentes algoritmos com o solver, e encontramos os mesmos problemas.

Haveria como fazermos uma chamada para podermos mostrar o problema e ver se conseguimos entender o que está errado? Pode ser amanhã antes da aula, se você estiver disponível.

Att,

Caio e Juliane.

**Comment by fccoelho** [comment]
Oi @Caioflp , podemos marcar hoje às 9 se vcs puderem.

**Comment by Caioflp** [comment]
Combinado, Professor.

**Comment by Caioflp** [comment]
> Oi @Caioflp , podemos marcar hoje às 9 se vcs puderem.

Professor, será no link da aula?
